apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
   POSTGRES_DB: aG9zdC5kb2NrZXIuaW50ZXJuYWw=
   POSTGRES_USER: cG9zdGdyZXM=
   POSTGRES_PASSWORD: SnVsaW8wMzIwMjA=
